version: 2.1
joba:
  builds:
    docker:
      - image: cimg/python:3.10.1
    steps:
      - checkout
      - run:
          name: install dependencies
          command: pip install -r requirements.txt
      - run:
          name: Run tests
          command: coverage run -m unittest && coverage xml && coverage report -m